language: php

php:
  - 5.4

before_script:
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
  - "sh -c 'git clone --branch=master --depth=100 --quiet https://github.com/Venne/sandbox http'"
  - "sh -c 'cd http && composer require venne/cms-module:2.0.x phpunit/phpunit-selenium:\">=1.2\" --prefer-dist'"
  - "sh -c 'cd http && php www/index.php venne:module:update'"
  - "sh -c 'cd http && php www/index.php venne:module:install cms --noconfirm'"
  - "sh -c 'cd http && php www/index.php cms:account admin admin'"
  - "sh -c 'cd http && php www/index.php cms:database:set --driver=pdo_sqlite --path=\"%tempDir%/database.db\"'"
  - "sh -c 'cd http && php www/index.php orm:schema-tool:create'"
  - "sh -c 'cd http && php www/index.php cms:language:add English en en'"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.28.0.jar > /dev/null 2>&1 &
  - sleep 3
  - php -S localhost:8000 -t http/www &
  - sleep 3

script: "sh -c 'cd http/vendor/venne/cms-module/ && php ./../../bin/phpunit'"
